base:
    model_name: ContextNet
    batch_size: 1024
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    net_regularizer: 1.0e-05
    epochs: 100
    eval_epoch: 2
    learning_rate: 0.0001
    loss: binary_crossentropy
    batch_normal: true
    optimizer: adam
    linear_dropout : 0.0
    num_workers: 16
    use_linear: True
    net_model: PFFN
    use_ce_every_layer: True
    increase_ratio: 2
    block_num: 3

