base:
    model_name: DCNv2
    batch_size: 1024
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    net_regularizer: 1.0e-05
    epochs: 100
    eval_epoch: 2
    learning_rate: 0.0001
    loss: binary_crossentropy
    batch_normal: true
    dropout: 0.0
    linear_dropout: 0.0
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    optimizer: adam
    num_workers: 16
    dcn_layers: 3
    net_model: Mix
    reduction: 8
    num_experts: 4
    structure: parallel
    use_linear: True
